<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.whl</groupId>
        <artifactId>whl-platform</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>whl-platform-system</artifactId>

    <description>
        system系统模块
    </description>

    <dependencies>
        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-platform-api</artifactId>
        </dependency>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-doc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-translation</artifactId>
        </dependency>

        <!-- OSS功能模块 -->
        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-oss</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-log</artifactId>
        </dependency>

        <!-- excel-->
        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-excel</artifactId>
        </dependency>

        <!-- SMS功能模块 -->
        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-tenant</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-security</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-idempotent</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-sensitive</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-encrypt</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-websocket</artifactId>
        </dependency>

        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-sse</artifactId>
        </dependency>

    </dependencies>

</project>
