<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.whl</groupId>
        <artifactId>whl-scm</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>whl-scm-wms</artifactId>
    <packaging>pom</packaging>

    <description>WMS 仓储管理（B1 起从 0 重建）</description>

    <modules>
        <module>whl-scm-wms-api</module>
        <module>whl-scm-wms-biz</module>
        <module>whl-scm-wms-admin-adapter</module>
    </modules>

</project>
