<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.whl</groupId>
        <artifactId>whl-framework</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>whl-framework-event</artifactId>
    <packaging>jar</packaging>

    <description>whl-framework-event 领域事件发布（单体 Spring Event，可演进 MQ）</description>

    <dependencies>
        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-kernel</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
    </dependencies>

</project>
