server:
  port: 9090
spring:
  application:
    name: whl-monitor-admin
  profiles:
    active: @profiles.active@

logging:
  config: classpath:logback-plus.xml

--- # 监控中心服务端配置
spring:
  security:
    user:
      name: @monitor.username@
      password: @monitor.password@
  boot:
    admin:
      ui:
        title: 供应链业务平台 — 服务监控中心
      context-path: /admin
  thymeleaf:
    check-template-location: false

--- # Actuator 监控端点的配置项
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/whl-monitor-admin.log

--- # 监控配置
spring.boot.admin.client:
  enabled: true
  url: http://localhost:9090/admin
  instance:
    service-host-type: IP
    metadata:
      username: ${spring.boot.admin.client.username}
      userpassword: ${spring.boot.admin.client.password}
  username: @monitor.username@
  password: @monitor.password@
