<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.whl</groupId>
        <artifactId>whl-framework</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>whl-framework-websocket</artifactId>

    <description>
        whl-framework-websocket 模块
    </description>

    <dependencies>
        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-satoken</artifactId>
        </dependency>
        <dependency>
            <groupId>com.whl</groupId>
            <artifactId>whl-framework-json</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>
